2019-04-07 21:56:00,490 INFO: Microblog startup [in /home/dark/flask_train/mainapp/__init__.py:48]
2019-04-07 22:03:16,557 INFO: Microblog startup [in /home/dark/flask_train/mainapp/__init__.py:48]
2019-04-07 22:18:53,353 INFO: Microblog startup [in /home/dark/flask_train/mainapp/__init__.py:50]
2019-04-07 22:21:34,228 INFO: Microblog startup [in /home/dark/flask_train/mainapp/__init__.py:50]
2019-04-08 15:31:53,729 INFO: Microblog startup [in /home/dark/flask_train/mainapp/__init__.py:51]
2019-04-08 15:31:56,460 ERROR: Exception on /index [GET] [in /home/dark/flask_train/flask_env/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/dark/flask_train/mainapp/routes.py", line 30, in index
    prev_url=prev_url)
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/dark/flask_train/mainapp/templates/base.html", line 45, in template
    {% block content %}
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/dark/flask_train/mainapp/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/dark/flask_train/mainapp/templates/base.html", line 45, in template
    {% block content %}
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/jinja2/environment.py", line 543, in _generate
    optimized=self.optimized)
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/jinja2/compiler.py", line 82, in generate
    generator.visit(node)
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/jinja2/visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/jinja2/compiler.py", line 718, in visit_Template
    self.fail('block %r defined twice' % block.name, block.lineno)
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/jinja2/compiler.py", line 315, in fail
    raise TemplateAssertionError(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateAssertionError: block 'content' defined twice
2019-04-08 15:33:29,775 INFO: Microblog startup [in /home/dark/flask_train/mainapp/__init__.py:51]
2019-04-08 15:33:32,246 ERROR: Exception on /index [GET] [in /home/dark/flask_train/flask_env/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/dark/flask_train/mainapp/routes.py", line 30, in index
    prev_url=prev_url)
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/dark/flask_train/mainapp/templates/base.html", line 69, in template
    {% block content %}
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/dark/flask_train/mainapp/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/dark/flask_train/mainapp/templates/base.html", line 69, in template
    {% block content %}
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/jinja2/environment.py", line 543, in _generate
    optimized=self.optimized)
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/jinja2/compiler.py", line 82, in generate
    generator.visit(node)
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/jinja2/visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/jinja2/compiler.py", line 718, in visit_Template
    self.fail('block %r defined twice' % block.name, block.lineno)
  File "/home/dark/flask_train/flask_env/lib/python3.7/site-packages/jinja2/compiler.py", line 315, in fail
    raise TemplateAssertionError(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateAssertionError: block 'content' defined twice
